from typing import Protocol

from project_planner.modules.artifacts.entities.Artifact import Artifact
from project_planner.modules.artifacts.entities.ArtifactKind import ArtifactKind
from project_planner.modules.artifacts.entities.ArtifactRevision import ArtifactRevision


class ArtifactRepository(Protocol):
    def save(self, artifact: Artifact) -> None: ...
    def create_if_absent(self, artifact: Artifact) -> Artifact: ...
    def get_for_project(self, project_id: str, kind: ArtifactKind) -> Artifact | None: ...
    def list_revisions(self, artifact_id: str) -> tuple[ArtifactRevision, ...]: ...
    def get_revision(self, artifact_id: str, revision_id: str) -> ArtifactRevision | None: ...
