from collections.abc import Sequence
from typing import Protocol

from project_planner.modules.projects.entities.ProjectCategory import ProjectCategory


class ProjectCategoryRepository(Protocol):
    def save(self, category: ProjectCategory) -> None: ...
    def get(self, category_id: str) -> ProjectCategory | None: ...
    def list_all(self) -> Sequence[ProjectCategory]: ...
    def delete(self, category_id: str) -> None: ...
