from collections.abc import Sequence
from typing import Protocol

from project_planner.modules.todos.entities.Todo import Todo
from project_planner.modules.todos.entities.TodoModule import TodoModule


class TodoRepository(Protocol):
    def save(self, todo: Todo) -> None: ...
    def get(self, todo_id: str) -> Todo | None: ...
    def list_for_project(self, project_id: str) -> Sequence[Todo]: ...
    def list_for_context(
        self, project_id: str, module: TodoModule, phase_id: str | None = None
    ) -> Sequence[Todo]: ...
    def delete(self, todo_id: str) -> None: ...
