from collections.abc import Sequence
from typing import Protocol

from project_planner.core.domain.agile.BacklogItem import BacklogItem
from project_planner.core.domain.agile.Sprint import Sprint


class AgileRepository(Protocol):
    def save_item(self, item: BacklogItem) -> None: ...
    def list_items(self, project_id: str, section_id: str | None) -> Sequence[BacklogItem]: ...
    def delete_item(self, item_id: str) -> None: ...
    def save_sprint(self, sprint: Sprint) -> None: ...
    def list_sprints(self, project_id: str, section_id: str | None) -> Sequence[Sprint]: ...
