from collections.abc import Sequence
from typing import Protocol

from project_planner.core.domain.projects.project import Project


class ProjectRepository(Protocol):
    def save(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project | None: ...
    def list_all(self) -> Sequence[Project]: ...
    def delete(self, project_id: str) -> None: ...
