from collections.abc import Sequence
from typing import Protocol

from project_planner.core.domain.custom.PlanningSection import PlanningSection
from project_planner.core.domain.custom.SectionItem import SectionItem


class SectionRepository(Protocol):
    def save(self, section: PlanningSection) -> None: ...
    def save_all(self, project_id: str, sections: Sequence[PlanningSection]) -> None: ...
    def get(self, section_id: str) -> PlanningSection | None: ...
    def list_for_project(self, project_id: str) -> Sequence[PlanningSection]: ...
    def delete(self, section_id: str) -> None: ...
    def save_item(self, item: SectionItem) -> None: ...
    def save_items(self, section_id: str, items: Sequence[SectionItem]) -> None: ...
    def get_item(self, item_id: str) -> SectionItem | None: ...
    def list_items(self, section_id: str) -> Sequence[SectionItem]: ...
    def delete_item(self, item_id: str) -> None: ...
