from collections.abc import Sequence
from typing import Protocol

from project_planner.modules.planning.entities.WaterfallTask import WaterfallTask


class WaterfallTaskRepository(Protocol):
    def save(self, task: WaterfallTask) -> None: ...
    def get(self, task_id: str) -> WaterfallTask | None: ...
    def list_for_phase(self, phase_id: str) -> Sequence[WaterfallTask]: ...
    def delete(self, task_id: str) -> None: ...
